FROM python:3.12-slim

WORKDIR /app

COPY api/rf_api/rfRequirements.txt .
RUN pip install --no-cache-dir -r rfRequirements.txt

COPY api/rf_api/main.py .
COPY models/rf.pkl ./models/rf.pkl

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
