FROM python:3.12-slim

WORKDIR /app

# Install CNN dependencies only
COPY api/cnn_api/cnnRequirements.txt .
RUN pip install --no-cache-dir -r cnnRequirements.txt

# Copy CNN API code
COPY api/cnn_api/main.py .

# Copy ONLY the CNN model
COPY models/cnn_weights.pth ./models/cnn_weights.pth

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
